name: bigStudy

on:
  workflow_dispatch:
  push:
    branches:
      - master

  schedule:
    - cron: '0 13 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Script
        env:
          COOKIE: ${{ secrets.COOKIE }}
          SEND_KEY: ${{ secrets.SEND_KEY }}
        run: |
          python main.py
