name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Install and update dependencies
      run: |
        pip install --upgrade -r requirements.txt
    - name: run
      run: |
        python main.py
